### ISSUE TITLE
Not able to generate URLs

### ISSUE THREAD

**Issue by AshishShukla16** [aseemgautam/google-sitemap#1]
I have provided the configuration as per documentation
`Sitemap sitemap = new Sitemap();
            sitemap.Add(new SitemapLocation
            {
                ChangeFrequency = SitemapLocation.eChangeFrequency.monthly,
                Url = "https://modernpathshala.com",
            });
           sitemap.WriteSitemapToFile(@"d://sitemap.xml")`

This is generating the blank file as output.

**Comment by dehghani-mehdi** [comment]
I tried your code and here is the content of generated file:

```xml
<?xml version="1.0"?>
<urlset xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://modernpathshala.com</loc>
    <changefreq>monthly</changefreq>
  </url>
</urlset>
```

Seems like everything works as expected.
